/*FILE HEADER -------------------------------------------------------------------------------------------------------
          File Name:  Calculator.java
             Author:  Nathan M. Abbey, 040-557-192
             Course:  CST8221 - Java Application Programming
        Lab Section:  301
  Assignment Number:  01
               Date:  October 19, 2017
          Professor:  Svillen Ranev
            Purpose:  This program build a calculator GUI for a user to interact with. It responds to events
                      generated by the GUI and displays the 'Action Command' on to the calculator display.
         Class List:  1. SplashScreen
         			  2. Calculator <--
         			  3. CalculatorViewController
         			  4. Controller (inner anonymous class)
 -------------------------------------------------------------------------------------------------------------------*/
/**
 * This is the class of the Calculator GUI program. with the main method. This class creates a JFRame object to act 
 * as the top layer of the calculator application. It then uses another class to setup all of the buttons and
 * display of the calculator object.
 *   
 * @author Nathan M. Abbey
 * @version 1.0
 * @see SplashScreen.java, CalculatorViewController.java
 * @since 1.8_066
 */

import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import javax.swing.BorderFactory;
import javax.swing.JFrame;


/**
 * This method creates a JFrame object and sets the content pane of that JFrame another class which
 * is responsible for creating and adding all of the calculator components. The method creates the
 * JFrame by specifying size, location for display, setting default close operation, setting up
 * a border around it, and setting the content pane to CalculatorViewController class.
 */
public class Calculator {
	
	/**Duration of the splash screen in milliseconds*/
	private static int SPLASH_DURATION = 5000; 

	public static void main(String[] args) {
	
		/**
		 * This is the SplashScreen class object that is used to launch the initial splash screen
		 * before the calculator application launches.
		 */
		SplashScreen sC = new SplashScreen(SPLASH_DURATION);
		sC.showSplashWindow();
		
		EventQueue.invokeLater(new Runnable(){

			/**Anonymous inner class with a 'run' method*/
			@Override
			public void run() {
			
				/**
				 * This JFrame object is the top-level container for the entire calculator
				 * application, it's content frame is set to CalculatorViewController. 
				 */
				JFrame topFrame = new JFrame("Calculator");
				
				// Sets the initial size, location, and default close operation of the JFrame
				topFrame.setMinimumSize(new Dimension(300, 460));
				topFrame.setPreferredSize(new Dimension(300, 460));
				topFrame.setLocationByPlatform(true);
				topFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				topFrame.setVisible(true);
				
				// Sets the content pane to CalculaotViewController and puts a border on the JFrame
				topFrame.setContentPane(new CalculatorViewController());	
				topFrame.getRootPane().setBorder(BorderFactory.createMatteBorder(5, 5, 5, 5, Color.BLACK));
			};
		});
	}
}